--- 
- name: Make sure that the Omeka directory exists
  sudo: true
  action: file path={{ omekadir }} state=directory
- name: Get Omeka
  get_url: dest=/tmp/omeka.zip  url=http://omeka.org/files/omeka-2.1.4.zip
- name: Unpack Omeka
  command: unzip -qo /tmp/omeka.zip -d {{ omekadir }}
- name: Move Omeka files ...sigh...
  raw: cp -r {{ omekadir }}/omeka-2.1.4/* {{ omekadir }}
- name: Move .htaccess
  raw: cp -r {{ omekadir }}/omeka-2.1.4/.htaccess {{ omekadir }}
- name: delete old Omeka directory
  raw: rm -rf {{ omekadir }}/omeka-2.1.4/
- include: omeka/playbook.yml